version: "3.9"

volumes:
  postgres_data:

services:
  web:
    build: .
    command: python main.py
    volumes:
      - .:/web/pharmasys
    ports:
      - 8080:8080
    depends_on:
      - local_pg

  local_pg:
    image: postgres:12
    command:
      - "postgres"
      - "-c"
      - "max_connections=500"
    environment:
      POSTGRES_DB: "pharmasys"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "kkk123"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    expose:
      - "5432"


  test_runner:
    build: .
    container_name: pytest_runner_works
    command: python -m pytest
    environment:
      - ENV=dev
    volumes:
      - .:/tests
